version: '3'

services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${POSTGRESQL_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRES_DB: ${POSTGRESQL_DATABASE}
    ports:
    - ${POSTGRESQL_PORT}:5432
    volumes:
    - ./data/postgresql:/var/lib/postgresql/data/
