// Code generated by mockery v2.0.0. DO NOT EDIT.

package scorestest

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// Earn provides a mock function with given fields: ctx, name, count
func (_m *Service) Earn(ctx context.Context, name string, count int) error {
	ret := _m.Called(ctx, name, count)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) error); ok {
		r0 = rf(ctx, name, count)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
